"use client";
import {FormEvent,useState} from "react";
type Content={heroTitle:string;heroDescription:string;studentCount:string;teacherCount:string};
export default function AdminPanel({initial}:{initial:Content}){const [status,setStatus]=useState("");
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Menyimpan...");const body=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch("/api/admin/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setStatus(res.ok?"Perubahan telah disimpan.":"Tidak dapat menyimpan perubahan.");}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Memuat naik gambar...");const res=await fetch("/api/admin/media",{method:"POST",body:new FormData(e.currentTarget)});setStatus(res.ok?"Gambar telah dimuat naik.":"Gambar gagal dimuat naik.");if(res.ok)e.currentTarget.reset();}
 return <><section className="admin-actions" aria-label="Tindakan Admin"><a href="#kemaskini-website"><span>✎</span><strong>Kemaskini Website</strong><small>Ubah tajuk, penerangan dan statistik sekolah</small></a><a href="#tambah-gambar"><span>＋</span><strong>Tambah Gambar Galeri</strong><small>Muat naik gambar baharu ke galeri sekolah</small></a></section>
 <form className="admin-card" id="kemaskini-website" onSubmit={save}><h2>Kemaskini website</h2><p className="admin-note">Bahagian ini hanya boleh digunakan oleh akaun Admin.</p><div className="admin-grid"><div className="field full"><label htmlFor="heroTitle">Tajuk utama</label><input id="heroTitle" name="heroTitle" defaultValue={initial.heroTitle} required/></div><div className="field full"><label htmlFor="heroDescription">Penerangan</label><textarea id="heroDescription" name="heroDescription" defaultValue={initial.heroDescription} required/></div><div className="field"><label htmlFor="studentCount">Bilangan murid</label><input id="studentCount" name="studentCount" defaultValue={initial.studentCount} required/></div><div className="field"><label htmlFor="teacherCount">Bilangan guru</label><input id="teacherCount" name="teacherCount" defaultValue={initial.teacherCount} required/></div></div><p><button className="save-button" type="submit">Simpan kemas kini website</button></p></form>
 <form className="admin-card" id="tambah-gambar" onSubmit={upload}><h2>Tambah gambar galeri</h2><p className="admin-note">Pilih gambar JPG, PNG atau WebP dengan saiz maksimum 8MB.</p><div className="admin-grid"><div className="field"><label htmlFor="image">Pilih gambar</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" required/></div><div className="field"><label htmlFor="category">Kategori</label><select id="category" name="category"><option>Kokurikulum</option><option>Pentadbiran</option><option>Program Sekolah</option></select></div><div className="field full"><label htmlFor="alt">Keterangan gambar</label><input id="alt" name="alt" placeholder="Contoh: Aktiviti murid" required/></div></div><p><button className="save-button" type="submit">Tambah gambar ke galeri</button></p></form><p className="status" aria-live="polite">{status}</p></>}
